# Generated by Django 5.2.8 on 2026-01-23 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('branch_address', models.TextField(blank=True)),
                ('account_number', models.CharField(max_length=64, unique=True)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'indexes': [models.Index(fields=['account_number'], name='OfficeApps__account_d99956_idx'), models.Index(fields=['swift_code'], name='OfficeApps__swift_c_d41100_idx')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2 code (e.g., IN, AE)', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='ISO code must be 2 letters', regex='^[A-Za-z]{2}$')])),
            ],
            options={
                'indexes': [models.Index(fields=['iso_code'], name='OfficeApps__iso_cod_0320fc_idx'), models.Index(fields=['name'], name='OfficeApps__name_c685dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incoterm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Incoterm',
                'verbose_name_plural': 'Incoterms',
                'indexes': [models.Index(fields=['code'], name='OfficeApps__code_b98d15_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_7d8a4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceOfReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Place of Receipt',
                'verbose_name_plural': 'Places of Receipt',
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_7b2060_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreCarriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pre-Carriage',
                'verbose_name_plural': 'Pre-Carriage',
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_dd5038_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignees', to='OfficeApps.country')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_df7660_idx'), models.Index(fields=['is_active'], name='OfficeApps__is_acti_a29b62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exporters', to='OfficeApps.country')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_4db8e9_idx'), models.Index(fields=['is_active'], name='OfficeApps__is_acti_8496d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinalDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_destinations', to='OfficeApps.country')),
            ],
            options={
                'verbose_name': 'Final Destination',
                'verbose_name_plural': 'Final Destinations',
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_1d6cbe_idx'), models.Index(fields=['country'], name='OfficeApps__country_e864a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_final_destination_per_country')],
            },
        ),
        migrations.CreateModel(
            name='PortOfDischarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ports_of_discharge', to='OfficeApps.country')),
            ],
            options={
                'verbose_name': 'Port of Discharge',
                'verbose_name_plural': 'Ports of Discharge',
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_e0da46_idx'), models.Index(fields=['country'], name='OfficeApps__country_9ac68d_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_discharge_port_per_country')],
            },
        ),
        migrations.CreateModel(
            name='PortOfLoading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ports_of_loading', to='OfficeApps.country')),
            ],
            options={
                'verbose_name': 'Port of Loading',
                'verbose_name_plural': 'Ports of Loading',
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_4c81ae_idx'), models.Index(fields=['country'], name='OfficeApps__country_1b7ac5_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_loading_port_per_country')],
            },
        ),
    ]
