# Generated by Django 5.2.8 on 2026-01-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0004_create_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditionsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('content_html', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Terms & Conditions Template',
                'verbose_name_plural': 'Terms & Conditions Templates',
                'indexes': [models.Index(fields=['name'], name='OfficeApps__name_2143c6_idx')],
            },
        ),
    ]
