# Generated by Django 5.2.8 on 2026-01-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0005_termsandconditionstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='bank_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='buyer_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='buyer_order_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='container_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='kind_of_packages',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='marks_and_nos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='other_references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='partial_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='place_of_receipt_by_pre_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_carrier_receipts', to='OfficeApps.placeofreceipt'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='terms_and_conditions_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='OfficeApps.termsandconditionstemplate'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='transshipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='validity_for_acceptance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='validity_for_shipment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='vessel_flight_no',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='proformainvoicelineitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proformainvoicelineitem',
            name='unit',
            field=models.CharField(default='MT', max_length=32),
        ),
    ]
