# Generated by Django 5.2.8 on 2026-01-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0006_proformainvoice_bank_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='OfficeApps.bankmaster'),
        ),
    ]
