# Generated by Django 5.2.8 on 2026-02-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0007_proformainvoice_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformainvoice',
            name='final_destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_invoices', to='OfficeApps.country'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_invoices', to='OfficeApps.country'),
        ),
    ]
