# Generated by Django 5.2.8 on 2026-02-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0008_proformainvoice_final_destination_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporter',
            name='iec_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='exporter',
            index=models.Index(fields=['iec_code'], name='OfficeApps__iec_cod_37f029_idx'),
        ),
    ]
