# Generated by Django 5.2.8 on 2026-02-09 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0009_exporter_iec_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_addresses', to='OfficeApps.country')),
                ('exporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_address_details', to='OfficeApps.exporter')),
            ],
            options={
                'verbose_name': 'Registered Address',
                'verbose_name_plural': 'Registered Addresses',
            },
        ),
        migrations.AddField(
            model_name='exporter',
            name='registered_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exporter_registered_address', to='OfficeApps.registeredaddress'),
        ),
        migrations.AddIndex(
            model_name='registeredaddress',
            index=models.Index(fields=['name'], name='OfficeApps__name_b11500_idx'),
        ),
        migrations.AddIndex(
            model_name='registeredaddress',
            index=models.Index(fields=['is_active'], name='OfficeApps__is_acti_17c5ff_idx'),
        ),
    ]
