# Generated by Django 5.2.8 on 2026-02-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0010_registeredaddress_exporter_registered_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporter',
            name='registered_address',
        ),
    ]
