# Generated by Django 5.2.8 on 2026-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0011_remove_exporter_registered_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
