# Generated by Django 5.2.8 on 2026-02-09 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0012_consignee_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REWORK', 'Rework'), ('PERMANENTLY_REJECTED', 'Permanently Rejected')], db_index=True, default='DRAFT', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reworked_at', models.DateTimeField(blank=True, null=True)),
                ('permanently_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('last_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_packing_lists', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_packing_lists', to=settings.AUTH_USER_MODEL)),
                ('proforma_invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='packing_list', to='OfficeApps.proformainvoice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['number'], name='OfficeApps__number_d5c3ef_idx'), models.Index(fields=['date'], name='OfficeApps__date_5593e4_idx'), models.Index(fields=['status'], name='OfficeApps__status_73c127_idx'), models.Index(fields=['proforma_invoice'], name='OfficeApps__proform_b9bbd2_idx')],
            },
        ),
    ]
