# Generated by Django 5.2.8 on 2026-02-09 13:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0013_packinglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to='OfficeApps.country')),
            ],
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proforma_invoices', to='OfficeApps.buyer'),
        ),
        migrations.AddIndex(
            model_name='buyer',
            index=models.Index(fields=['name'], name='OfficeApps__name_ebbb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='buyer',
            index=models.Index(fields=['is_active'], name='OfficeApps__is_acti_f988e4_idx'),
        ),
    ]
