# Generated by Django 5.2.8 on 2026-02-09 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0014_buyer_proformainvoice_buyer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingListContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('container_reference', models.CharField(blank=True, max_length=128)),
                ('marks_and_numbers', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingListContainerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=50)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('packages_number_and_kind', models.CharField(max_length=128)),
                ('description_of_goods', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(max_length=32)),
                ('batch_details', models.CharField(blank=True, max_length=128)),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=14)),
                ('tare_weight', models.DecimalField(decimal_places=3, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='packinglist',
            name='OfficeApps__proform_b9bbd2_idx',
        ),
        migrations.RemoveField(
            model_name='packinglist',
            name='permanently_rejected_at',
        ),
        migrations.AddField(
            model_name='packinglist',
            name='bl_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='bl_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists', to='OfficeApps.buyer'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='consignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists', to='OfficeApps.consignee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packinglist',
            name='exporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists', to='OfficeApps.exporter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packinglist',
            name='lc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='lc_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='notify_party',
            field=models.TextField(blank=True, help_text='Can be a dropdown or free text'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='other_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='other_ref_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='po_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='so_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='so_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='proforma_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_list', to='OfficeApps.proformainvoice'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REWORK', 'Rework')], db_index=True, default='DRAFT', max_length=32),
        ),
        migrations.AddIndex(
            model_name='packinglist',
            index=models.Index(fields=['consignee'], name='OfficeApps__consign_8a3d8d_idx'),
        ),
        migrations.AddField(
            model_name='packinglistcontainer',
            name='packing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='OfficeApps.packinglist'),
        ),
        migrations.AddField(
            model_name='packinglistcontaineritem',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='OfficeApps.packinglistcontainer'),
        ),
    ]
