# Generated by Django 5.2.8 on 2026-02-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0016_alter_packinglist_consignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinglist',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists', to='OfficeApps.consignee'),
        ),
        migrations.AlterField(
            model_name='packinglist',
            name='exporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists', to='OfficeApps.exporter'),
        ),
    ]
