# Generated by Django 5.2.8 on 2026-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0017_alter_packinglist_consignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglistcontaineritem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
            preserve_default=False,
        ),
    ]
