# Generated by Django 5.2.8 on 2026-02-10 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0018_packinglistcontaineritem_gross_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='final_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_final_destination', to='OfficeApps.finaldestination'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='final_destination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destination_packing_lists', to='OfficeApps.country'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='incoterm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_incoterm', to='OfficeApps.incoterm'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_packing_lists', to='OfficeApps.country'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_payment_term', to='OfficeApps.paymentterm'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='place_of_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_place_of_receipt', to='OfficeApps.placeofreceipt'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='place_of_receipt_by_pre_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pl_pre_carrier_receipts', to='OfficeApps.placeofreceipt'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='port_discharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_port_discharge', to='OfficeApps.portofdischarge'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='port_loading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_port_loading', to='OfficeApps.portofloading'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='pre_carriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_lists_pre_carriage', to='OfficeApps.precarriage'),
        ),
        migrations.AddField(
            model_name='packinglist',
            name='vessel_flight_no',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
