# Generated by Django 5.2.8 on 2026-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0019_packinglist_final_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
