# Generated by Django 5.2.8 on 2026-02-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0020_packinglist_invoice_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packinglistcontaineritem',
            name='gross_weight',
        ),
        migrations.RemoveField(
            model_name='packinglistcontaineritem',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='packinglistcontaineritem',
            name='tare_weight',
        ),
    ]
