# Generated by Django 5.2.8 on 2026-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0022_uom_alter_packinglistcontaineritem_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uom',
            name='rate_per_uom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
