# Generated by Django 5.2.8 on 2026-02-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0023_alter_uom_rate_per_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglistcontainer',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='packinglistcontainer',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='packinglistcontainer',
            name='tare_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
