# Generated by Django 5.2.8 on 2026-02-10 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0024_packinglistcontainer_gross_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled')], db_index=True, default='DRAFT', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='OfficeApps.bankmaster')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='OfficeApps.buyer')),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='OfficeApps.consignee')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='OfficeApps.exporter')),
                ('incoterm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='OfficeApps.incoterm')),
                ('last_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_commercial_invoices', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_commercial_invoices', to=settings.AUTH_USER_MODEL)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='OfficeApps.paymentterm')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialInvoiceAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled'), ('PDF_DRAFT_DOWNLOADED', 'Draft PDF Downloaded'), ('PDF_DOWNLOADED', 'PDF Downloaded')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoice_actions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='OfficeApps.commercialinvoice')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommercialInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('hs_code', models.CharField(blank=True, max_length=50)),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(default='MT', max_length=32)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='OfficeApps.commercialinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='commercialinvoice',
            index=models.Index(fields=['number'], name='OfficeApps__number_ffa0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialinvoice',
            index=models.Index(fields=['date'], name='OfficeApps__date_d994ed_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialinvoice',
            index=models.Index(fields=['status'], name='OfficeApps__status_824f24_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialinvoice',
            index=models.Index(fields=['consignee'], name='OfficeApps__consign_c68856_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialinvoiceaudittrail',
            index=models.Index(fields=['invoice'], name='OfficeApps__invoice_fcb3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialinvoiceaudittrail',
            index=models.Index(fields=['timestamp'], name='OfficeApps__timesta_245581_idx'),
        ),
    ]
