# Generated by Django 5.2.8 on 2026-02-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0025_commercialinvoice_commercialinvoiceaudittrail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='packing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commercial_invoices', to='OfficeApps.packinglist'),
        ),
    ]
