# Generated by Django 5.2.8 on 2026-02-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeApps', '0026_commercialinvoice_packing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='fob_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='commercialinvoice',
            name='lc_details',
            field=models.TextField(blank=True),
        ),
    ]
